// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWIy_p30-d9JNehChI-0d1LdWUqj0WDvY',
    appId: '1:36207856100:web:2ec12c3678f999c1401ff1',
    messagingSenderId: '36207856100',
    projectId: 'liveasy-assn',
    authDomain: 'liveasy-assn.firebaseapp.com',
    storageBucket: 'liveasy-assn.appspot.com',
    measurementId: 'G-SLW8G95P2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDttFewN6NjEIL3x0rPVYztxNzkVdk1cb0',
    appId: '1:36207856100:android:ae446c19c5410da6401ff1',
    messagingSenderId: '36207856100',
    projectId: 'liveasy-assn',
    storageBucket: 'liveasy-assn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdn_7sGqrK6Ohiwqu2fQmYyv3VH83G1Fs',
    appId: '1:36207856100:ios:bf5b145b91018ed1401ff1',
    messagingSenderId: '36207856100',
    projectId: 'liveasy-assn',
    storageBucket: 'liveasy-assn.appspot.com',
    iosBundleId: 'com.example.liveasyAssn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdn_7sGqrK6Ohiwqu2fQmYyv3VH83G1Fs',
    appId: '1:36207856100:ios:bf5b145b91018ed1401ff1',
    messagingSenderId: '36207856100',
    projectId: 'liveasy-assn',
    storageBucket: 'liveasy-assn.appspot.com',
    iosBundleId: 'com.example.liveasyAssn',
  );
}
